### ISSUE TITLE
Various errors

### ISSUE THREAD

**Issue by Q3CPMA** [4re/vapoursynth-portage#31] opened 2016-03-12 20:31 UTC
`vapoursynth-plugins-meta` doesn't work because of a whitespace missing at L108 of `vapoursynth-plugins-meta-3.ebuild`

`vapoursynth-dfftest-3` failed to compile with this error:
```
DFTTest/DFTTest.cpp: At global scope:
DFTTest/DFTTest.cpp:1573:1: error: ‘__m128d selectd(const __m128d&, const __m128d&, const __m128d&)’ conflicts with a previous declaration
 }
 ^
In file included from DFTTest/vectorclass/vectorclass.h:51:0,
                 from DFTTest/vectorclass/vectormath_common.h:35,
                 from DFTTest/vectorclass/vectormath_exp.h:34,
                 from DFTTest/DFTTest.cpp:33:
DFTTest/vectorclass/vectorf256.h:67:23: note: previous declaration ‘__m256d selectd(const __m256d&, const __m256d&, const __m256d&)’
 static inline __m256d selectd (__m256d const & s, __m256d const & a, __m256d const & b) {
                       ^
In file included from DFTTest/vectorclass/vectorclass.h:42:0,
                 from DFTTest/vectorclass/vectormath_common.h:35,
                 from DFTTest/vectorclass/vectormath_exp.h:34,
                 from DFTTest/DFTTest.cpp:33:
DFTTest/vectorclass/vectorf128.h:71:23: note: -fabi-version=6 (or =0) avoids this error with a change in mangling
 static inline __m128d selectd (__m128d const & s, __m128d const & a, __m128d const & b) {
```

**Comment by 4re** [comment] 2016-03-13 01:12
The typo in the ebuild should be fixed now, but I can't reproduce your problem with `=edia-plugins/vapoursynth-dfttest-3`.
Can you provide me with the output of `emerge --info`?

**Comment by Q3CPMA** [comment] 2016-03-13 01:41
https://bpaste.net/show/f8ea37d261d5

**Comment by 4re** [comment] 2016-03-13 23:36
I will revert back all the ebuilds affected by this bug to use `-mno-avx` instead of `-mno-xop` so GCC 4 doesn't complain about this.

If you find again this bug in any other ebuild just reopen this issue and make me know about it.

**Closed by 4re** 2016-03-13 23:36 UTC

**Comment by HolyWu** [comment] 2016-03-14 14:19
Try if the latest commit works when you compiling without `-mno-avx`.

**Comment by Q3CPMA** [comment] 2016-03-14 18:56
It works now.

**Comment by Q3CPMA** [comment] 2016-03-15 22:50
@4re In case you didn't notice, dfttest now works again with avx.

**Comment by 4re** [comment] 2016-03-15 23:33
Yes, the only ebuilds with injected compiler flags are stable releases affected by the bug, live ebuilds don't have them. Thx for testing.
